version: '3.8'

services:
  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENABLED: "true"
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      COMMON_STORAGETYPE: minio
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-08-16T20-17-30Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data
    ports:
      - "9001:9000"

  # Uncomment to enable Redis for caching
  # redis:
  #   image: redis:7.2
  #   container_name: hoardermcp-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes

  # Uncomment to enable Langfuse for observability
  # langfuse:
  #   image: ghcr.io/langfuse/langfuse:latest
  #   container_name: hoardermcp-langfuse
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  #     - NEXTAUTH_URL=http://localhost:3000
  #     - NEXTAUTH_SECRET=your-secret-here
  #     - SALT=your-salt-here
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres:15
  #   container_name: hoardermcp-postgres
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  milvus_data:
  etcd_data:
  minio_data:
  # redis_data:
  # postgres_data:
